(()=>{'use strict';
const d=window.ATLAS_RECORDS;if(!d)return;
const main=document.querySelector('main');
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function head(t,s){return `<header class="page-head"><span class="eyebrow">AI & Onderwijs Atlas</span><h1>${e(t)}</h1><p class="lead">${e(s)}</p></header>`}
function about(){
  const records=d.records||[];
  main.innerHTML=head('Over de atlas','Een gratis, open en brongebaseerde wegwijzer voor bestaand aanbod rond AI in het onderwijs.')+`<section class="section"><div class="detail"><article><h2>Waarom deze atlas bestaat</h2><p>AI in het onderwijs bestaat uit wetgeving, publieke infrastructuur, kennisorganisaties, programma’s, voorzieningen en lokale toepassingen. De Atlas brengt deze lagen bij elkaar, zodat onderwijsprofessionals sneller kunnen vinden wat al bestaat en bij welke organisatie zij terechtkunnen.</p><h2>Maker</h2><p>De AI & Onderwijs Atlas Nederland is gemaakt door <strong>Eva Willems</strong>. Voor vragen over het concept of samenwerking kunt u mailen naar <a href="mailto:evac.m.willems@proton.me">evac.m.willems@proton.me</a>.</p><h2>Uitgangspunten</h2><div class="principle-list"><section><h3>Open</h3><p>Broncode, correcties en bijdragen zijn openbaar. Persoonlijke voorkeuren blijven uitsluitend in uw eigen browser.</p></section><section><h3>Controleerbaar</h3><p>Elke publieke vermelding verwijst naar een officiële bron en toont wanneer die voor het laatst is gecontroleerd.</p></section><section><h3>Corrigeerbaar</h3><p>Organisaties en gebruikers kunnen bestaand, ontbrekend of verouderd aanbod via een vaste bijdrageroute melden.</p></section></div><h2>Zorgvuldige afbakening</h2><p>De Atlas is geen keurmerk, ranglijst of aanbevelingssysteem. Een vermelding betekent dat het aanbod en een officiële bron zijn vastgelegd, niet dat Eva Willems het product of de organisatie inhoudelijk aanbeveelt. Brede financieringsregelingen worden als zodanig benoemd en deadlines en voorwaarden moeten altijd bij de officiële bron worden gecontroleerd.</p></article><aside class="factbox"><h2>Over het project</h2><dl><dt>Maker</dt><dd>Eva Willems</dd><dt>Contact</dt><dd><a href="mailto:evac.m.willems@proton.me">evac.m.willems@proton.me</a></dd><dt>Versie</dt><dd>${e(d.metadata.version)}</dd><dt>Bijgewerkt</dt><dd>${e(d.metadata.updated)}</dd><dt>Gepubliceerd aanbod</dt><dd>${records.length}</dd></dl></aside></div></section>`;
}
function beheer(){
  const r=d.records||[],stale=r.filter(x=>x.lastVerified&&((Date.now()-Date.parse(x.lastVerified))/86400000)>90);
  main.innerHTML=head('Datakwaliteit en beheer','Transparantie over de kwaliteit en actualiteit van het gepubliceerde aanbod.')+`<section class="section"><div class="stats">${[['Gepubliceerde records',r.length],['Met officiële bron',r.filter(x=>x.sourceUrls.some(s=>s.sourceType==='official')).length],['Ouder dan 90 dagen',stale.length],['Recent geverifieerd',r.filter(x=>['verified','recently_checked'].includes(x.verificationStatus)).length],['Gebroken bronnen',r.filter(x=>x.verificationStatus==='broken_source').length]].map(([a,b])=>`<div class="stat"><strong>${b}</strong><span>${a}</span></div>`).join('')}</div><div class="notice"><strong>Laatste datasetupdate: ${e(d.metadata.updated)}</strong><br>De publieke catalogus bevat alleen brongecontroleerde records die daadwerkelijk aanbod beschrijven.</div></section>`;
}
function changes(){
  const all=d.records.flatMap(x=>(x.changeHistory||[]).map(c=>({...c,title:x.title}))).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
  main.innerHTML=head('Wijzigingen','Publieke inhoudelijke geschiedenis zonder technische commitdetails.')+`<section class="section"><div class="result-list">${all.slice(0,100).map(x=>`<article class="result-card"><div><span class="badge">${e(x.type)}</span><h2>${e(x.title)}</h2><p>${e(x.summary)}</p><small>${e(x.date)}</small></div></article>`).join('')||'<div class="empty">Nog geen wijzigingen geregistreerd.</div>'}</div></section>`;
}
function route(){const p=(location.hash.slice(1)||'').split('?')[0];if(p==='over')about();if(p==='beheer')beheer();if(p==='wijzigingen')changes()}
addEventListener('hashchange',route);route();
})();