/* Vraaggestuurde vindplaats bovenop de atlaszoekfunctie. */
(()=>{'use strict';
const popular=['Subsidie','Training','Handreiking','Voorziening','Programma','Wetgeving'];
const icons={Subsidie:'€',Training:'↗',Handreiking:'▤',Voorziening:'◆',Programma:'◎',Wetgeving:'§'};
function relabel(select,title,first){if(!select)return;const label=select.closest('label');label.childNodes[0].textContent=title;select.options[0].textContent=first}
function enhance(){const filters=document.querySelector('.filters'),results=document.querySelector('#results'),toolbar=document.querySelector('.toolbar');if(!filters||!results||filters.dataset.marketplace)return;filters.dataset.marketplace='true';filters.closest('.section')?.classList.add('marketplace-section');filters.classList.add('marketplace-filters');filters.insertAdjacentHTML('afterbegin','<div class="filter-intro"><span class="eyebrow">Verfijn je vraag</span><h2>Wat zoek je?</h2><p>Vind snel passend en actueel aanbod.</p></div>');
const q=filters.querySelector('#q'),sector=filters.querySelector('#sector'),type=filters.querySelector('#type'),status=filters.querySelector('#status');q?.closest('label')?.classList.add('filter-search');relabel(sector,'Voor welk onderwijsniveau?','Alle niveaus');relabel(type,'Wat voor soort aanbod?','Alle soorten');relabel(status,'Beschikbaarheid','Alle statussen');
type?.closest('label')?.insertAdjacentHTML('afterend',`<fieldset class="quick-types"><legend>Veel gezocht</legend>${popular.map(x=>`<button type="button" data-type="${x}"><span class="type-icon" aria-hidden="true">${icons[x]}</span>${x}</button>`).join('')}</fieldset>`);
const shell=document.createElement('div'),area=document.createElement('div');shell.className='marketplace-layout';area.className='marketplace-results';area.innerHTML='<div class="results-heading"><span class="eyebrow">Gevonden aanbod</span><h2>Resultaten</h2><p class="freshness">De getoonde resultaten reageren direct op je filters. Bronactualiteit: <strong>juli 2026</strong>.</p></div>';filters.parentNode.insertBefore(shell,filters);shell.append(filters,area);area.append(toolbar,results);
document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{const on=b.classList.toggle('active');document.querySelectorAll('[data-type]').forEach(x=>x!==b&&x.classList.remove('active'));type.value=on?b.dataset.type:'';type.dispatchEvent(new Event('input',{bubbles:true}))});type?.addEventListener('input',()=>document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===type.value)));decorate();new MutationObserver(decorate).observe(results,{childList:true,subtree:true})}
function decorate(){document.querySelectorAll('#results .card:not([data-decorated])').forEach(c=>{c.dataset.decorated='true';const meta=c.querySelector('.muted');if(meta)meta.insertAdjacentHTML('beforebegin','<span class="card-label">Onderwijsniveau</span>');c.insertAdjacentHTML('beforeend','<span class="card-cta">Bekijk details →</span>')})}
addEventListener('hashchange',()=>setTimeout(enhance));new MutationObserver(enhance).observe(document.querySelector('main'),{childList:true});enhance()})();
