"""Voeg gecontroleerde subsidies, calls en direct bruikbaar aanbod toe.

Alle records in deze tranche zijn op 21 juli 2026 gecontroleerd aan de hand
van een officiële bron. Brede financieringsregelingen worden expliciet als
niet AI-exclusief omschreven; zo blijft de catalogus omvangrijk én eerlijk.
"""

import json
from pathlib import Path


ROOT = Path(__file__).parents[1]
RECORDS_PATH = ROOT / "data" / "records.json"
META_PATH = ROOT / "data" / "metadata.json"
VERIFIED = "2026-07-21"


def record(identifier, title, kind, legacy, provider, description, purpose,
           audiences, sectors, themes, url, keywords, *, geography="Nederland",
           cost="free", availability="Direct beschikbaar", status="available",
           publication=None, start=None, end=None, language=None,
           organization_ids=None, related_ids=None, parent_ids=None,
           funding_amount=None, funding_min=None, funding_max=None,
           total_budget=None, application_open=None, deadline=None,
           eligibility=None, applicant_types=None, call_status=None,
           recurrence=None, notes=None):
    return {
        "id": identifier,
        "title": title,
        "recordType": kind,
        "legacyType": legacy,
        "subtype": None,
        "organizationIds": organization_ids or [],
        "providerName": provider,
        "description": description,
        "purpose": purpose,
        "audiences": audiences,
        "sectors": sectors,
        "themes": themes,
        "status": status,
        "availabilityText": availability,
        "startDate": start,
        "endDate": end,
        "publicationDate": publication,
        "lastVerified": VERIFIED,
        "verificationStatus": "verified",
        "sourceUrls": [{"label": "Officiële bron", "url": url, "sourceType": "official"}],
        "relatedIds": related_ids or [],
        "parentIds": parent_ids or [],
        "childIds": [],
        "geographicScope": geography,
        "accessType": "public",
        "costType": cost,
        "fundingAmount": funding_amount,
        "fundingDeadline": deadline,
        "applicationOpenDate": application_open,
        "applicationDeadline": deadline,
        "fundingMin": funding_min,
        "fundingMax": funding_max,
        "totalBudget": total_budget,
        "eligibility": eligibility,
        "applicantTypes": applicant_types or [],
        "callStatus": call_status,
        "recurrence": recurrence,
        "language": language or ["nl"],
        "keywords": keywords,
        "notes": notes,
        "changeHistory": [{
            "date": VERIFIED,
            "type": "added",
            "summary": "Toegevoegd in gecontroleerde inhoudstranche 4."
        }],
    }


ALL = ["PO", "VO", "MBO", "HBO", "WO", "Onderzoek", "Overheid"]

ITEMS = [
    # Organisaties: ook rechtstreeks vindbaar per onderwijssector.
    record("rijksuniversiteit-groningen", "Rijksuniversiteit Groningen", "organization", "Organisatie", "Rijksuniversiteit Groningen",
           "Nederlandse universiteit met een centraal AI Office, docenttrainingen en een open module voor kritische AI-geletterdheid.",
           "Onderwijs, onderzoek en verantwoorde toepassing van AI ondersteunen.",
           ["Docenten", "Studenten", "Onderzoekers", "Onderwijsadviseurs"], ["WO", "Onderzoek"],
           ["AI-geletterdheid", "Professionalisering", "Onderzoek"], "https://www.rug.nl/",
           ["RUG", "Groningen", "AI Office", "AI-geletterdheid"]),
    record("erasmus-universiteit-rotterdam", "Erasmus Universiteit Rotterdam", "organization", "Organisatie", "Erasmus Universiteit Rotterdam",
           "Nederlandse universiteit met trainingen en ondersteuning voor docenten die generatieve AI verantwoord willen toepassen.",
           "Onderwijs en professionalisering rond generatieve AI ondersteunen.",
           ["Docenten", "Studenten", "Onderzoekers", "Onderwijsadviseurs"], ["WO", "Onderzoek"],
           ["Professionalisering", "Lesgeven en leren met AI"], "https://www.eur.nl/",
           ["EUR", "Rotterdam", "generatieve AI", "docenten"]),
    record("hogeschool-van-amsterdam", "Hogeschool van Amsterdam", "organization", "Organisatie", "Hogeschool van Amsterdam",
           "Nederlandse hogeschool die samen met de UvA een instellingsgestuurde AI-chatomgeving voor onderwijs en onderzoek aanbiedt.",
           "Praktijkgericht onderwijs, onderzoek en veilige AI-toepassing ondersteunen.",
           ["Docenten", "Studenten", "Onderzoekers", "IT-professionals"], ["HBO", "Onderzoek"],
           ["Veilige AI-omgeving", "Lesgeven en leren met AI"], "https://www.hva.nl/",
           ["HvA", "hogeschool", "AI Chat"]),
    record("jisc", "Jisc", "organization", "Organisatie", "Jisc",
           "Britse non-profitorganisatie voor digitale voorzieningen, kennis en professionalisering in vervolg- en hoger onderwijs.",
           "Onderwijsinstellingen ondersteunen bij betrouwbare digitale en AI-transformatie.",
           ["Docenten", "Bestuurders", "IT-professionals", "Onderwijsadviseurs"], ["MBO", "HBO", "WO", "Onderzoek"],
           ["Beleid en governance", "Professionalisering", "Data en infrastructuur"], "https://www.jisc.ac.uk/",
           ["Jisc", "tertiary education", "National Centre for AI"], geography="Internationaal", language=["en"]),
    record("teqsa", "Tertiary Education Quality and Standards Agency (TEQSA)", "organization", "Organisatie", "TEQSA",
           "Australische onafhankelijke toezichthouder met publieke kennisbronnen over generatieve AI, toetsing en onderwijskwaliteit.",
           "Hoger onderwijs ondersteunen bij kwaliteitsborging in een AI-geïntegreerde omgeving.",
           ["Bestuurders", "Examencommissies", "Docenten", "Toezichthouders"], ["HBO", "WO"],
           ["Toetsing en examinering", "Beleid en governance"], "https://www.teqsa.gov.au/",
           ["TEQSA", "quality assurance", "assessment", "GenAI"], geography="Internationaal", language=["en"]),
    record("teachai", "TeachAI", "organization", "Organisatie", "TeachAI",
           "Internationaal initiatief dat scholen en overheden ondersteunt met open richtlijnen, beleid en hulpmiddelen voor AI in het onderwijs.",
           "Verantwoorde en inclusieve invoering van AI in het funderend onderwijs ondersteunen.",
           ["Docenten", "Schoolleiders", "Beleidsmakers"], ["PO", "VO"],
           ["Beleid en governance", "AI-geletterdheid", "Curriculumontwikkeling"], "https://www.teachai.org/",
           ["TeachAI", "schools", "policy", "AI guidance"], geography="Internationaal", language=["en"]),
    record("spencer-foundation", "Spencer Foundation", "organization", "Organisatie", "Spencer Foundation",
           "Internationale stichting die onderzoek financiert dat bijdraagt aan verbetering en transformatie van onderwijs.",
           "Onderwijsonderzoek en duurzame systeemverandering financieren.",
           ["Onderzoekers", "Onderwijsinstellingen", "Consortia"], ["Onderzoek", "HBO", "WO"],
           ["Subsidies en financiering", "Onderzoek"], "https://www.spencer.org/",
           ["Spencer Foundation", "education research", "grants"], geography="Internationaal", language=["en"]),
    record("national-science-foundation", "National Science Foundation (NSF)", "organization", "Organisatie", "National Science Foundation",
           "Amerikaanse publieke onderzoeksfinancier met programma's voor informatica-, AI- en computeronderwijs.",
           "Fundamenteel en toegepast onderzoek en onderwijsinnovatie financieren.",
           ["Onderzoekers", "Universiteiten", "Onderwijsinstellingen"], ["PO", "VO", "MBO", "HBO", "WO", "Onderzoek"],
           ["Subsidies en financiering", "Onderzoek", "AI-geletterdheid"], "https://www.nsf.gov/",
           ["NSF", "research funding", "AI education", "computing education"], geography="Internationaal", language=["en"]),
    record("roc-mondriaan", "ROC Mondriaan", "organization", "Organisatie", "ROC Mondriaan",
           "Mbo-instelling die met MondriAI werkt aan verantwoorde, inclusieve en duurzame toepassing van AI.",
           "Mbo-onderwijs en professionalisering rond AI ontwikkelen.",
           ["Docenten", "Studenten", "Bestuurders", "Onderwijsontwikkelaars"], ["MBO"],
           ["AI-geletterdheid", "Implementatie en adoptie"], "https://www.rocmondriaan.nl/",
           ["ROC Mondriaan", "MondriAI", "MBO", "AI"]),
    record("zadkine", "Zadkine", "organization", "Organisatie", "Zadkine",
           "Mbo-instelling die AI-agents toepast in ondersteunende processen en medewerkers daarvoor professionaliseert.",
           "Mbo-onderwijs en bedrijfsvoering met verantwoorde AI-toepassing ondersteunen.",
           ["Docenten", "Ondersteunend personeel", "Bestuurders", "Studenten"], ["MBO"],
           ["Implementatie en adoptie", "Professionalisering"], "https://www.zadkine.nl/",
           ["Zadkine", "MBO", "AI-agents", "professionalisering"]),
    record("hogeschool-inholland", "Hogeschool Inholland", "organization", "Organisatie", "Hogeschool Inholland",
           "Nederlandse hogeschool met praktijktoepassingen van generatieve AI als leer- en feedbackpartner.",
           "Praktijkgericht onderwijs en onderzoek rond betekenisvolle AI-toepassing ontwikkelen.",
           ["Docenten", "Studenten", "Onderzoekers", "Onderwijsontwikkelaars"], ["HBO", "Onderzoek"],
           ["Praktijkvoorbeelden", "Lesgeven en leren met AI"], "https://www.inholland.nl/",
           ["Inholland", "Holli", "AI-feedback", "hogeschool"]),

    # Actuele nationale en internationale financiering.
    record("ciiic-learning-communities-november-2026", "CIIIC Learning Communities – indieningsronde november 2026", "funding_call", "Call", "Regieorgaan SIA",
           "Open call voor duurzame learning communities rond immersieve ervaringen, met samenwerking tussen onderzoek, onderwijs en praktijk.",
           "Kennisontwikkeling en professionalisering rond immersieve technologie structureel verbinden.",
           ["Hogescholen", "Onderzoekers", "Consortia", "Bedrijven"], ["HBO", "MBO", "WO", "Onderzoek"],
           ["Subsidies en financiering", "Professionalisering", "Onderzoek"],
           "https://regieorgaan-sia.nl/financiering/ciiic-learning-communities/indieningsronde-november-2026/",
           ["CIIIC", "learning communities", "immersive experience", "call"], status="open_call",
           availability="Open; deadline 3 november 2026 om 14.00 uur", application_open="2026-05-07", deadline="2026-11-03",
           funding_amount="€900.000 tot €1.800.000 per aanvraag", funding_min=900000, funding_max=1800000, total_budget=10800000,
           eligibility="Consortia van onderwijs, onderzoek en praktijk; minimaal 20% cofinanciering. Zie de call voor de volledige voorwaarden.",
           applicant_types=["Hogescholen", "Universiteiten", "Onderzoeksorganisaties", "Bedrijven", "Publieke organisaties"], call_status="open_call"),
    record("raak-mkb-september-2026", "RAAK-mkb – indieningsronde september 2026", "funding_call", "Call", "Regieorgaan SIA",
           "Open regeling voor praktijkgericht onderzoek van hogescholen met minimaal zes mkb-bedrijven. Niet uitsluitend voor AI; AI- en EdTech-vraagstukken zijn mogelijk wanneer ze aantoonbaar uit de praktijk komen.",
           "Nieuwe kennis ontwikkelen en toepassen voor concrete innovatievragen van het mkb.",
           ["Hogescholen", "Onderzoekers", "Consortia", "Bedrijven"], ["HBO", "Onderzoek"],
           ["Subsidies en financiering", "Onderzoek", "Implementatie en adoptie"], "https://regieorgaan-sia.nl/financiering/raak-mkb/",
           ["RAAK-mkb", "praktijkgericht onderzoek", "AI", "EdTech"], status="open_call",
           availability="Open; deadline uiterlijk 22 september 2026", deadline="2026-09-22", funding_max=375000,
           eligibility="Aanvraag door een hogeschool in samenwerking met ten minste zes mkb-ondernemingen; regeling is breder dan AI.",
           applicant_types=["Hogescholen", "Mkb-bedrijven", "Consortia"], call_status="open_call", recurrence="Periodiek"),
    record("kiem-maatschappelijk-verdienvermogen-september-2026", "KIEM Maatschappelijk Verdienvermogen – september 2026", "funding_call", "Call", "Regieorgaan SIA",
           "Open KIEM-ronde voor kortlopend praktijkgericht onderzoek naar maatschappelijke verdiencapaciteit. Niet AI-exclusief; bruikbaar voor verantwoorde AI-vraagstukken met een concrete praktijkpartner.",
           "Nieuwe samenwerkingen en eerste onderzoeksactiviteiten rond maatschappelijke transities mogelijk maken.",
           ["Hogescholen", "Onderzoekers", "Consortia", "Bedrijven"], ["HBO", "Onderzoek", "Overheid"],
           ["Subsidies en financiering", "Publieke waarden en ethiek", "Onderzoek"], "https://regieorgaan-sia.nl/financiering/kiem/kiem-mv/",
           ["KIEM MV", "maatschappelijk verdienvermogen", "verantwoorde AI"], status="open_call",
           availability="Open; tweede ophaalmoment 15 september 2026", deadline="2026-09-15", funding_max=40000, total_budget=1820302,
           eligibility="Hogeschool met praktijkpartners; regeling is breder dan AI. Controleer de volledige callvoorwaarden.",
           applicant_types=["Hogescholen", "Praktijkpartners", "Consortia"], call_status="open_call"),
    record("kiem-hightech-september-2026", "KIEM HighTech – september 2026", "funding_call", "Call", "Regieorgaan SIA",
           "Open KIEM-ronde voor verkennend praktijkgericht onderzoek naar sleuteltechnologieën en digitalisering. Niet uitsluitend voor onderwijs of AI.",
           "Nieuwe samenwerkingen rond hightech- en digitaliseringsvraagstukken starten.",
           ["Hogescholen", "Onderzoekers", "Consortia", "Bedrijven"], ["HBO", "Onderzoek"],
           ["Subsidies en financiering", "Data en infrastructuur", "Onderzoek"], "https://regieorgaan-sia.nl/financiering/kiem/kiem-hightech/",
           ["KIEM HighTech", "digitalisering", "sleuteltechnologie", "AI"], status="open_call",
           availability="Open; tweede ophaalmoment 15 september 2026", deadline="2026-09-15", funding_max=40000,
           eligibility="Hogeschool met praktijkpartners; regeling is breder dan AI en onderwijs.",
           applicant_types=["Hogescholen", "Bedrijven", "Consortia"], call_status="open_call"),
    record("professional-doctorate-technologie-digitalisering-2026", "Professional Doctorate – Technologie & Digitalisering 2026", "funding_call", "Call", "Regieorgaan SIA",
           "Financiering voor kandidaten in een Professional Doctorate-traject, waaronder het domein Technologie & Digitalisering. De regeling is breder dan AI.",
           "Professionals opleiden die complexe praktijkvraagstukken door onderzoekend handelen vernieuwen.",
           ["Hogescholen", "Onderzoekers", "Consortia"], ["HBO", "Onderzoek"],
           ["Subsidies en financiering", "Professionalisering", "Onderzoek"], "https://regieorgaan-sia.nl/financiering/professional-doctorate/",
           ["Professional Doctorate", "Technologie en Digitalisering", "PD"], status="open_call",
           availability="Ophaalmomenten op 10 september en 12 november 2026", deadline="2026-11-12", funding_max=271400,
           eligibility="Nederlandse hogescholen met een erkend PD-programma; regeling is breder dan AI.",
           applicant_types=["Hogescholen"], call_status="open_call", recurrence="Meerdere ophaalmomenten per jaar"),
    record("take-off-hbo-najaar-2026", "Take-off hbo – najaarsronde 2026", "funding_call", "Call", "Regieorgaan SIA",
           "Verwachte najaarsronde voor haalbaarheidsstudies naar commerciële toepassing van kennis en innovaties uit hogescholen. Niet uitsluitend voor AI of onderwijs.",
           "Onderzoekers en studenten helpen een innovatieve kennisgedreven onderneming te verkennen.",
           ["Hogescholen", "Onderzoekers", "Studenten", "Bedrijven"], ["HBO", "Onderzoek"],
           ["Subsidies en financiering", "Implementatie en adoptie"], "https://regieorgaan-sia.nl/financiering/take-off-hbo/",
           ["Take-off hbo", "haalbaarheidsstudie", "startup", "AI"], status="planned",
           availability="Najaarsronde verwacht in september 2026; exacte deadline nog niet gepubliceerd", funding_max=50000,
           eligibility="Onderzoekers, studenten en kennisbenutters verbonden aan een Nederlandse hogeschool; regeling is breder dan AI.",
           applicant_types=["Hogescholen", "Onderzoekers", "Studenten"], call_status="forthcoming", recurrence="Periodiek"),
    record("comenius-leadership-fellows-2027", "Comenius Leadership Fellows 2027", "funding_call", "Call", "Nationaal Kennisinstituut Onderwijs",
           "Subsidieronde voor omvangrijke onderwijsinnovatieprojecten in het hoger onderwijs. Niet AI-exclusief; projecten rond verantwoord AI-onderwijs kunnen passen wanneer zij aan de regeling voldoen.",
           "Duurzame onderwijsinnovatie en instellingsbrede verandering in het hoger onderwijs ondersteunen.",
           ["Docenten", "Hogescholen", "Universiteiten", "Onderwijsontwikkelaars"], ["HBO", "WO"],
           ["Subsidies en financiering", "Implementatie en adoptie", "Curriculumontwikkeling"],
           "https://zoek.officielebekendmakingen.nl/stcrt-2026-17923.html",
           ["Comenius", "Leadership Fellows", "onderwijsinnovatie", "AI"], status="open_call",
           availability="Intentieverklaring 10 september; volledige aanvraag 29 oktober 2026", application_open="2026-06-04", deadline="2026-10-29",
           funding_max=500000, total_budget=2000000,
           eligibility="Onderwijsprofessionals in het bekostigd hoger onderwijs; regeling is breder dan AI.",
           applicant_types=["Hogescholen", "Universiteiten", "Onderwijsprofessionals"], call_status="open_call", recurrence="Jaarlijks"),
    record("open-journals-onderwijsonderzoek-2026", "Open Journals – onderwijsonderzoek 2026", "funding_call", "Call", "Nationaal Kennisinstituut Onderwijs",
           "Doorlopende subsidie voor Nederlandse wetenschappelijke tijdschriften over onderwijsonderzoek die volledig open access willen werken. Niet specifiek voor AI.",
           "Open toegang tot resultaten van onderwijsonderzoek bevorderen.",
           ["Onderzoekers", "Onderzoeksorganisaties", "Universiteiten"], ["HBO", "WO", "Onderzoek"],
           ["Subsidies en financiering", "Onderzoek", "Data en infrastructuur"], "https://www.officielebekendmakingen.nl/stcrt-2026-7642.html",
           ["Open Journals", "open access", "onderwijsonderzoek", "tijdschrift"], status="open_call",
           availability="Doorlopend tot het subsidieplafond is bereikt", funding_max=17500, total_budget=70000,
           eligibility="Nederlandse wetenschappelijke tijdschriften die onderwijsonderzoek publiceren en aan de regeling voldoen.",
           applicant_types=["Wetenschappelijke tijdschriften", "Onderzoeksorganisaties"], call_status="open_call"),
    record("eu-code-week-tender-2027-2030", "Europese aanbesteding EU Code Week 2027–2030", "funding_call", "Call", "Europese Commissie",
           "Europese aanbesteding voor uitvoering en opschaling van EU Code Week, inclusief leermiddelen, docentprofessionalisering en communityvorming. Dit is een tender, geen subsidie.",
           "Digitale vaardigheden en programmeeronderwijs in Europa opschalen.",
           ["Consortia", "Bedrijven", "Onderwijsorganisaties", "Overheden"], ["PO", "VO", "MBO", "HBO"],
           ["Subsidies en financiering", "AI-geletterdheid", "Professionalisering"],
           "https://digital-strategy.ec.europa.eu/en/funding/call-tenders-eu-code-week-2027-2030",
           ["EU Code Week", "tender", "digital skills", "teacher training"], geography="Europa", language=["en"], status="open_call",
           availability="Aanbesteding open; deadline 15 september 2026 om 16.00 uur CET", application_open="2026-07-09", deadline="2026-09-15",
           eligibility="Inschrijvers die aan de Europese aanbestedingsvoorwaarden voldoen.", applicant_types=["Consortia", "Bedrijven", "Onderwijsorganisaties"], call_status="open_call"),
    record("spencer-vision-grants-2026", "Spencer Foundation Vision Grants 2026", "funding_call", "Call", "Spencer Foundation",
           "Internationale call voor het ontwikkelen van grootschalige onderzoeksprogramma's gericht op transformatie van onderwijssystemen. Niet specifiek voor AI.",
           "Interdisciplinaire onderzoeksagenda's voor duurzame verandering in onderwijs ontwikkelen.",
           ["Onderzoekers", "Consortia", "Onderwijsinstellingen"], ["HBO", "WO", "Onderzoek"],
           ["Subsidies en financiering", "Onderzoek", "Beleid en governance"], "https://www.spencer.org/grant_types/vision-grants",
           ["Spencer", "Vision Grants", "education systems", "research"], geography="Internationaal", language=["en"], status="open_call",
           availability="Intentie uiterlijk 12 augustus; volledige aanvraag 16 september 2026", application_open="2026-06-04", deadline="2026-09-16",
           eligibility="Internationale onderzoeksteams volgens de officiële call; regeling is breder dan AI.",
           applicant_types=["Onderzoekers", "Consortia", "Onderzoeksorganisaties"], call_status="open_call"),
    record("nsf-computing-education-research", "NSF Computing Education Research", "subsidy", "Subsidie", "National Science Foundation",
           "Actief Amerikaans financieringsprogramma voor onderzoek naar onderwijs en leren in computing, waaronder artificiële intelligentie, op alle onderwijsniveaus.",
           "Kennisbasis en onderwijspaden voor computer- en AI-onderwijs versterken.",
           ["Onderzoekers", "Universiteiten", "Onderwijsinstellingen"], ["PO", "VO", "MBO", "HBO", "WO", "Onderzoek"],
           ["Subsidies en financiering", "Onderzoek", "AI-geletterdheid"], "https://www.nsf.gov/funding/opportunities/computing-education-research",
           ["NSF", "Computing Education Research", "AI education", "funding"], geography="Internationaal", language=["en"],
           availability="Actief programma; controleer de officiële pagina voor actuele indienmomenten",
           eligibility="Amerikaanse instellingen en partners volgens de NSF-voorwaarden; Nederlandse partijen kunnen niet zonder meer als hoofdaanvrager indienen.",
           applicant_types=["Universiteiten", "Onderzoeksorganisaties", "Onderwijsinstellingen"]),
    record("nsf-k12-ai-education-resources", "NSF Expanding K-12 Resources for AI Education", "subsidy", "Subsidie", "National Science Foundation",
           "Aanvullende financiering voor bestaande NSF-projecten die hoogwaardige leermiddelen, curricula, docentprofessionalisering of netwerken voor AI-onderwijs in K-12 uitbreiden.",
           "Toegang tot betrouwbare middelen en professionalisering voor AI-onderwijs vergroten.",
           ["Onderzoekers", "Onderwijsinstellingen", "Docenten"], ["PO", "VO", "Onderzoek"],
           ["Subsidies en financiering", "AI-geletterdheid", "Curriculumontwikkeling", "Professionalisering"],
           "https://www.nsf.gov/funding/opportunities/dcl-expanding-k-12-resources-ai-education",
           ["NSF", "K-12", "AI education", "curriculum", "teacher professional development"], geography="Internationaal", language=["en"],
           availability="Actieve aanvullende financiering voor bestaande NSF-awardees", funding_max=300000,
           eligibility="Alleen bestaande NSF-awardees die aan de Dear Colleague Letter voldoen.", applicant_types=["Bestaande NSF-awardees"]),

    # Trainingen en professionalisering.
    record("rug-critical-ai-literacy-module", "Critical AI Literacy Module", "training", "Training", "Rijksuniversiteit Groningen",
           "Open zelfstudiemodule van ongeveer twee uur over kritisch, verantwoord en transparant gebruik van generatieve AI in studie, onderwijs en onderzoek.",
           "Studenten en medewerkers een gedeeld fundament voor kritische AI-geletterdheid geven.",
           ["Studenten", "Docenten", "Onderzoekers", "Medewerkers"], ["HBO", "WO", "Onderzoek"],
           ["AI-geletterdheid", "Professionalisering", "Publieke waarden en ethiek"],
           "https://www.rug.nl/library/education-and-research/information-literacy/ai-module",
           ["RUG", "critical AI literacy", "self-study", "module"], geography="Internationaal", language=["en"], publication="2026-07-06"),
    record("rug-ai-office-courses-workshops", "AI Office – cursussen en workshops", "service", "Voorziening", "Rijksuniversiteit Groningen",
           "Centraal actueel overzicht van trainingen, workshops en ondersteuning voor medewerkers en docenten rond AI.",
           "Gebruikers naar passend professionaliseringsaanbod van de RUG leiden.",
           ["Docenten", "Onderzoekers", "Medewerkers", "Onderwijsadviseurs"], ["WO", "Onderzoek"],
           ["Professionalisering", "AI-geletterdheid", "Implementatie en adoptie"],
           "https://www.rug.nl/cit/services/ai-office/advies-en-training/courses-workshops",
           ["RUG AI Office", "courses", "workshops", "training"]),
    record("eur-ai-voor-docenten-beginners", "How to use AI as a teacher – beginners", "training", "Training", "Erasmus Universiteit Rotterdam",
           "Praktische introductie van drie uur voor docenten en tutoren, met basiskennis, kansen, beperkingen en verantwoorde toepassing van AI in onderwijs.",
           "Docenten zelfstandig en kritisch met generatieve AI laten starten.",
           ["Docenten", "Onderwijsadviseurs", "Ondersteunend personeel"], ["WO"],
           ["AI-geletterdheid", "Professionalisering", "Lesgeven en leren met AI"],
           "https://www.eur.nl/en/educational-innovation/programme/how-use-ai-teacher-beginners",
           ["EUR", "AI for teachers", "beginners", "microcredential"], cost="free", language=["en"], availability="Nieuwe editie wordt verwacht; belangstelling kan worden doorgegeven", status="planned"),
    record("eur-generative-ai-academic-questions", "Generative AI for Academic Questions", "training", "Training", "Erasmus Universiteit Rotterdam",
           "Gratis online training van zes uur over het zorgvuldig gebruiken en beoordelen van generatieve AI bij academische vragen.",
           "Docenten en professionals leren generatieve AI verantwoord in een academische context toe te passen.",
           ["Docenten", "Onderzoekers", "Onderwijsadviseurs"], ["HBO", "WO", "Onderzoek"],
           ["AI-geletterdheid", "Professionalisering", "Onderzoek"],
           "https://www.eur.nl/onderwijsinnovatie/cursus/generative-ai-academic-questions",
           ["EUR", "academic questions", "online course", "GenAI"], cost="free", language=["en"], availability="Online en op aanvraag"),
    record("jisc-ethical-responsible-ai-education", "Ethical and responsible AI in education", "training", "Training", "Jisc",
           "Zelfstudiecursus van 45 tot 60 minuten over ethische en verantwoorde keuzes bij gebruik van AI in onderwijs.",
           "Onderwijsprofessionals praktische kaders geven voor verantwoord AI-gebruik.",
           ["Docenten", "Bestuurders", "Onderwijsadviseurs", "IT-professionals"], ["MBO", "HBO", "WO"],
           ["Publieke waarden en ethiek", "AI-geletterdheid", "Professionalisering"],
           "https://www.jisc.ac.uk/training/ethical-and-responsible-ai-in-education",
           ["Jisc", "ethical AI", "responsible AI", "self-paced"], geography="Internationaal", cost="freemium", language=["en"], availability="Zelfstudie; maandelijks komen nieuwe plaatsen beschikbaar"),
    record("jisc-ai-literacy-module-understanding-ai", "AI literacy for teaching and learning – Understanding AI", "training", "Training", "Jisc",
           "Downloadbare introductiemodule van 45 tot 60 minuten met slides, activiteiten en begeleidersnotities over wat AI is en hoe het onderwijs raakt.",
           "Teams een herbruikbare basisworkshop voor AI-geletterdheid bieden.",
           ["Docenten", "Onderwijsadviseurs", "Onderwijsontwikkelaars"], ["MBO", "HBO", "WO"],
           ["AI-geletterdheid", "Professionalisering"],
           "https://www.jisc.ac.uk/training/ai-literacy-for-teaching-and-learning-module-1-understanding-ai",
           ["Jisc", "AI literacy", "facilitator", "downloadable module"], geography="Internationaal", cost="free", language=["en"]),
    record("comenius-npuls-peergang-digitale-transformatie", "Peergang Digitale Transformatie", "training", "Training", "ComeniusNetwerk en Npuls",
           "Praktijkgericht programma voor duo's uit onderwijs en ondersteuning die aan een concrete digitale vernieuwing werken, zoals AI, blended learning of digitale geletterdheid.",
           "Digitale onderwijsinnovatie duurzaam van idee naar uitvoering brengen.",
           ["Docenten", "Onderwijsadviseurs", "Onderwijsontwikkelaars"], ["MBO", "HBO", "WO"],
           ["Professionalisering", "Implementatie en adoptie", "AI-geletterdheid"],
           "https://comeniusnetwerk.nl/nieuws/3258810.aspx?t=Wil-jij-digitale-vernieuwing-echt-van-de-grond-krijgen-",
           ["ComeniusNetwerk", "Npuls", "peergang", "digitale transformatie"], cost="free", publication="2026-05-12", availability="Aanmelden via de officiële programmapagina"),

    # Handreikingen en kennisvoorzieningen.
    record("oecd-digital-education-outlook-2026", "OECD Digital Education Outlook 2026", "guidance", "Handreiking", "OECD",
           "Internationaal evidence-overzicht over effectieve inzet van generatieve AI in onderwijs, met aandacht voor leren, docentrol, infrastructuur, beleid en menselijke regie.",
           "Onderwijspraktijk en beleid baseren op internationale evidentie over generatieve AI.",
           ["Beleidsmakers", "Bestuurders", "Docenten", "Onderzoekers"], ALL,
           ["Onderzoek", "Lesgeven en leren met AI", "Beleid en governance", "Publieke waarden en ethiek"],
           "https://www.oecd.org/en/publications/2026/01/oecd-digital-education-outlook-2026_940e0dd8.html",
           ["OECD", "Digital Education Outlook 2026", "GenAI", "evidence"], geography="Internationaal", language=["en"], publication="2026-01-19"),
    record("oecd-vijf-principes-ai-beroepsonderwijs", "Five principles for effective AI use in vocational education and training development", "guidance", "Handreiking", "OECD",
           "Vijf principes voor mensgerichte, uitlegbare en gecontroleerde toepassing van AI bij ontwikkeling van beroepsonderwijs en kwalificaties.",
           "Beroepsonderwijs ondersteunen bij bestuurbare en verantwoorde inzet van AI in curriculumontwikkeling.",
           ["Beleidsmakers", "Onderwijsontwikkelaars", "Bestuurders", "Docenten"], ["MBO", "HBO", "Onderzoek", "Overheid"],
           ["Curriculumontwikkeling", "Beleid en governance", "Publieke waarden en ethiek"],
           "https://www.oecd.org/en/publications/five-principles-for-the-effective-use-of-ai-in-vocational-education-and-training-development_ee8c8e8e-en/full-report.html",
           ["OECD", "VET", "vocational education", "human oversight", "AI governance"], geography="Internationaal", language=["en"], publication="2026-06-24"),
    record("jisc-ai-maturity-toolkit", "AI maturity toolkit for tertiary education", "guidance", "Handreiking", "Jisc",
           "Praktisch volwassenheidsmodel met vijf niveaus en thema's voor strategie, studenten, medewerkers, academische integriteit en veilig gebruik.",
           "Instellingen helpen hun huidige AI-volwassenheid bepalen en gerichte vervolgstappen kiezen.",
           ["Bestuurders", "Beleidsmakers", "IT-professionals", "Onderwijsadviseurs"], ["MBO", "HBO", "WO"],
           ["Beleid en governance", "Implementatie en adoptie", "Veilige AI-omgeving"],
           "https://www.jisc.ac.uk/ai-maturity-toolkit-for-tertiary-education",
           ["Jisc", "AI maturity", "toolkit", "academic integrity"], geography="Internationaal", language=["en"]),
    record("jisc-leading-ai-colleges-framework", "Leading AI in colleges: a strategic framework", "guidance", "Handreiking", "Jisc",
           "Strategisch raamwerk voor AI-leiderschap rond vaardigheden en cultuur, technologie, governance en datavolwassenheid.",
           "Bestuurders en teams helpen AI-invoering als samenhangende organisatieverandering te sturen.",
           ["Bestuurders", "Beleidsmakers", "IT-professionals", "Onderwijsadviseurs"], ["MBO", "HBO"],
           ["Beleid en governance", "Implementatie en adoptie", "Data en infrastructuur"],
           "https://www.jisc.ac.uk/guides/leading-ai-in-colleges-a-strategic-framework",
           ["Jisc", "strategic framework", "college", "AI leadership"], geography="Internationaal", language=["en"], publication="2025-11-17"),
    record("jisc-ai-environmental-sustainability", "AI and environmental sustainability in post-16 education", "guidance", "Handreiking", "Jisc",
           "Praktisch en evidence-gebaseerd rapport over milieu-impact van AI en stappen die onderwijsinstellingen kunnen nemen bij inkoop, gebruik en governance.",
           "Milieueffecten expliciet meewegen in bestuurlijke keuzes over AI.",
           ["Bestuurders", "IT-professionals", "Inkoop", "Beleidsmakers"], ["MBO", "HBO", "WO", "Onderzoek"],
           ["Publieke waarden en ethiek", "Beleid en governance", "Data en infrastructuur"],
           "https://www.jisc.ac.uk/reports/ai-and-environmental-sustainability-in-post-16-education",
           ["Jisc", "sustainability", "environment", "AI procurement"], geography="Internationaal", language=["en"], publication="2026-06-24"),
    record("teqsa-assessment-reform-ai", "Assessment reform for the age of artificial intelligence", "guidance", "Handreiking", "TEQSA",
           "Principes en voorstellen voor toetsbeleid dat leeruitkomsten blijft borgen en studenten voorbereidt op verantwoord AI-gebruik.",
           "Instellingen helpen toetsing en kwaliteitsborging structureel aan te passen aan generatieve AI.",
           ["Docenten", "Examencommissies", "Bestuurders", "Toetsmakers"], ["HBO", "WO"],
           ["Toetsing en examinering", "Beleid en governance", "Lesgeven en leren met AI"],
           "https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assessment-reform-age-artificial-intelligence",
           ["TEQSA", "assessment reform", "GenAI", "learning assurance"], geography="Internationaal", language=["en"]),
    record("teqsa-adaptive-capabilities-genai", "Assuring quality learning in a gen AI-integrated future", "guidance", "Handreiking", "TEQSA",
           "Actuele handreiking met evidence-gebaseerde, toepasbare benaderingen voor leerkwaliteit, kritisch denken, ethisch redeneren en adaptieve vaardigheden in een AI-geïntegreerde toekomst.",
           "Kwaliteit van leren en menselijke correctiecapaciteit onder AI-condities borgen.",
           ["Docenten", "Examencommissies", "Bestuurders", "Onderwijsontwikkelaars"], ["HBO", "WO"],
           ["Toetsing en examinering", "AI-geletterdheid", "Publieke waarden en ethiek"],
           "https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities",
           ["TEQSA", "adaptive capabilities", "learning assurance", "critical thinking"], geography="Internationaal", language=["en"], publication="2026-06-24"),
    record("teqsa-genai-knowledge-hub", "TEQSA Gen AI knowledge hub", "service", "Voorziening", "TEQSA",
           "Publieke kennisbank met samenhangende bronnen over generatieve AI, toetsing, academische integriteit en kwaliteitsborging in hoger onderwijs.",
           "Instellingen één actuele ingang bieden naar onderbouwde GenAI-kennis en praktijkvoorbeelden.",
           ["Docenten", "Examencommissies", "Bestuurders", "Onderwijsadviseurs"], ["HBO", "WO"],
           ["Toetsing en examinering", "Beleid en governance", "Praktijkvoorbeelden"],
           "https://www.teqsa.gov.au/guides-resources/higher-education-good-practice-hub/gen-ai-knowledge-hub",
           ["TEQSA", "Gen AI knowledge hub", "academic integrity"], geography="Internationaal", language=["en"]),
    record("australian-framework-generative-ai-schools", "Australian Framework for Generative AI in Schools", "standard", "Standaard", "Australian Government Department of Education",
           "Nationaal kader met principes en leidende uitspraken voor verantwoord en ethisch gebruik van generatieve AI in scholen.",
           "Scholen ondersteunen bij consistente keuzes over leren, welzijn, transparantie, privacy, veiligheid en menselijke regie.",
           ["Docenten", "Schoolleiders", "Bestuurders", "Beleidsmakers"], ["PO", "VO"],
           ["Beleid en governance", "Publieke waarden en ethiek", "Privacy en AVG"],
           "https://www.education.gov.au/schooling/resources/australian-framework-generative-artificial-intelligence-ai-schools",
           ["Australian Framework", "schools", "GenAI", "human oversight"], geography="Internationaal", language=["en"]),
    record("teachai-guidance-schools-toolkit", "AI Guidance for Schools Toolkit", "guidance", "Handreiking", "TeachAI",
           "Open toolkit voor schoolbeleid met leidende vragen, voorbeeldteksten, implementatiestappen en aandacht voor verantwoord gebruik van AI.",
           "Schoolleiders en teams helpen praktisch, uitlegbaar en aanpasbaar AI-beleid te maken.",
           ["Schoolleiders", "Bestuurders", "Beleidsmakers", "Docenten"], ["PO", "VO"],
           ["Beleid en governance", "Implementatie en adoptie", "AI-geletterdheid"], "https://www.teachai.org/toolkit",
           ["TeachAI", "school guidance", "policy toolkit", "responsible AI"], geography="Internationaal", language=["en"]),
    record("dfe-generative-ai-product-safety-standards", "Generative AI product safety standards for education", "standard", "Standaard", "UK Department for Education",
           "Publieke veiligheidsstandaarden voor leveranciers en onderwijsinstellingen, met eisen rond filtering, logging, beveiliging, privacy, intellectueel eigendom en bescherming tegen manipulatie.",
           "Onderwijsorganisaties concrete criteria geven voor beoordeling en inkoop van generatieve AI-producten.",
           ["IT-professionals", "Inkoop", "Bestuurders", "Leveranciers"], ["PO", "VO", "MBO"],
           ["Veilige AI-omgeving", "Privacy en AVG", "Beleid en governance"],
           "https://www.gov.uk/government/publications/generative-ai-product-safety-standards/generative-ai-product-safety-standards",
           ["DfE", "product safety standards", "procurement", "GenAI"], geography="Internationaal", language=["en"], publication="2026-01-19"),
    record("ofqual-ai-coursework-resources-schools", "AI in coursework: resources for schools", "guidance", "Handreiking", "Ofqual",
           "Lesplan en leiderschapspakket voor zorgvuldig gebruik van AI bij beoordeeld werk, gericht op leerlingen, docenten en schoolleiding.",
           "Scholen helpen de geldigheid en integriteit van coursework onder generatieve AI te beschermen.",
           ["Docenten", "Schoolleiders", "Toetsmakers", "Leerlingen"], ["VO", "MBO"],
           ["Toetsing en examinering", "AI-geletterdheid", "Beleid en governance"],
           "https://www.gov.uk/government/publications/ai-in-coursework-resources-for-schools",
           ["Ofqual", "coursework", "assessment", "AI"], geography="Internationaal", language=["en"], publication="2026-03-09"),
    record("qaa-generative-ai-resource-hub", "QAA Generative AI resource hub", "service", "Voorziening", "Quality Assurance Agency for Higher Education",
           "Publieke thematische kennisbank met kwaliteitszorg, beleid, toetsing en praktijkbronnen over generatieve AI in hoger onderwijs.",
           "Hogeronderwijsinstellingen snel naar relevante, gecureerde GenAI-bronnen leiden.",
           ["Docenten", "Examencommissies", "Bestuurders", "Onderwijsadviseurs"], ["HBO", "WO"],
           ["Toetsing en examinering", "Beleid en governance", "Lesgeven en leren met AI"],
           "https://www.qaa.ac.uk/sector-resources/generative-artificial-intelligence",
           ["QAA", "resource hub", "quality assurance", "generative AI"], geography="Internationaal", language=["en"]),

    # Producten en praktijkvoorbeelden, feitelijk en zonder onbewezen claims.
    record("feedbackfruits-ai-practice", "FeedbackFruits AI Practice", "product", "Product", "FeedbackFruits",
           "Onderwijsactiviteit waarin studenten doelgericht met een AI-assistent oefenen en docenten de interactie kunnen opnemen in begeleiding en evaluatie. De functie wordt als bèta aangeboden.",
           "AI-geletterdheid oefenen binnen een door de docent ontworpen leeractiviteit.",
           ["Docenten", "Studenten", "Onderwijsontwikkelaars"], ["MBO", "HBO", "WO"],
           ["AI-geletterdheid", "Lesgeven en leren met AI", "Toetsing en examinering"],
           "https://feedbackfruits.com/solutions/ai-practice",
           ["FeedbackFruits", "AI Practice", "AI literacy", "learning activity"], geography="Internationaal", cost="paid", language=["en"], status="pilot", availability="Bèta; beschikbaar via deelnemende instellingen"),
    record("d2l-lumi-pro", "D2L Lumi Pro", "product", "Product", "D2L",
           "Verzameling door beheerders inschakelbare AI-functies in Brightspace voor onder meer quizvragen, leeruitkomsten, samenvattingen, studiemateriaal en contentbewerking.",
           "Docenten en studenten binnen de bestaande leeromgeving ondersteunen met configureerbare AI-functies.",
           ["Docenten", "Studenten", "IT-professionals", "Onderwijsontwikkelaars"], ["MBO", "HBO", "WO"],
           ["Lesgeven en leren met AI", "Implementatie en adoptie", "Veilige AI-omgeving"],
           "https://community.d2l.com/brightspace/kb/articles/26332-about-d2l-lumi-pro",
           ["D2L Lumi Pro", "Brightspace", "quiz", "study support"], geography="Internationaal", cost="paid", language=["en"]),
    record("canvas-igniteai", "Canvas IgniteAI", "product", "Product", "Instructure",
           "Samenhangende AI-functies binnen Canvas voor onderwijsontwerp, begeleiding en werkprocessen, met instellingen en docenten als regisseur van gebruik.",
           "AI-ondersteuning in de leeromgeving integreren zonder losse gebruikersroutes.",
           ["Docenten", "Studenten", "IT-professionals", "Onderwijsontwikkelaars"], ["MBO", "HBO", "WO"],
           ["Lesgeven en leren met AI", "Implementatie en adoptie", "Veilige AI-omgeving"],
           "https://www.instructure.com/products/canvas-tiers",
           ["Canvas IgniteAI", "Instructure", "LMS", "educator control"], geography="Internationaal", cost="paid", language=["en"], availability="Gefaseerd wereldwijd beschikbaar uiterlijk 15 augustus 2026"),
    record("uva-hva-ai-chat", "UvA/HvA AI Chat", "service", "Voorziening", "Universiteit van Amsterdam en Hogeschool van Amsterdam",
           "Instellingsgestuurde chatomgeving waarmee studenten en medewerkers generatieve AI binnen een beheerde onderwijscontext kunnen gebruiken.",
           "Veilig experimenteren en werken met generatieve AI binnen institutionele kaders mogelijk maken.",
           ["Studenten", "Docenten", "Onderzoekers", "Medewerkers"], ["HBO", "WO", "Onderzoek"],
           ["Veilige AI-omgeving", "Lesgeven en leren met AI", "Implementatie en adoptie"],
           "https://www.surf.nl/index.php/nieuws/winnaars-surf-onderwijsawards-2025-brengen-vernieuwing-van-ai-tot-robotica",
           ["UvA", "HvA", "AI Chat", "veilige omgeving"], publication="2025-12-09"),
    record("miec-data-ai-mbo", "MIEC Data & AI in het mbo", "practice_example", "Praktijkvoorbeeld", "MBO Digitaal",
           "Praktijkvoorbeeld van een meerjarig expertisecentrum dat mbo-instellingen ondersteunt bij verantwoorde integratie van data en AI in curriculum, vaardigheden en governance.",
           "Kennis, voorbeelden en professionalisering rond data en AI tussen mbo-instellingen delen.",
           ["Docenten", "Bestuurders", "Onderwijsontwikkelaars", "IT-professionals"], ["MBO"],
           ["Praktijkvoorbeelden", "AI-geletterdheid", "Beleid en governance"],
           "https://mbodigitaal.nl/wp-content/uploads/2026/03/Factsheet-MIEC-DATA-AI.pdf",
           ["MIEC", "MBO Digitaal", "Data en AI", "expertisecentrum"], publication="2026-03-01"),
    record("zadkine-ai-agents-bedrijfsvoering", "AI-agents in de bedrijfsvoering van Zadkine", "practice_example", "Praktijkvoorbeeld", "Zadkine",
           "Mbo-praktijkvoorbeeld waarin AI-agents worden ingezet in ondersteunende processen, gecombineerd met professionalisering en kritische beoordeling van output.",
           "Laten zien hoe een mbo-instelling AI in bedrijfsvoering invoert met aandacht voor medewerkers en kwaliteitscontrole.",
           ["Ondersteunend personeel", "Bestuurders", "IT-professionals", "Docenten"], ["MBO"],
           ["Praktijkvoorbeelden", "Implementatie en adoptie", "Professionalisering"],
           "https://mbodigitaal.nl/wp-content/uploads/2026/03/Factsheet-Zadkine.pdf",
           ["Zadkine", "AI-agents", "bedrijfsvoering", "MBO"], publication="2026-03-01"),
    record("roc-mondriaan-mondriai", "MondriAI bij ROC Mondriaan", "practice_example", "Praktijkvoorbeeld", "ROC Mondriaan",
           "Instellingsbrede mbo-aanpak voor verantwoorde, inclusieve en duurzame AI, met aandacht voor AI-geletterdheid, curriculum en toetsing.",
           "AI als samenhangende onderwijs- en organisatieverandering vormgeven.",
           ["Docenten", "Bestuurders", "Onderwijsontwikkelaars", "Studenten"], ["MBO"],
           ["Praktijkvoorbeelden", "AI-geletterdheid", "Toetsing en examinering"],
           "https://mbodigitaal.nl/wp-content/uploads/2026/03/Factsheet-ROC-Mondriaan.pdf",
           ["MondriAI", "ROC Mondriaan", "MBO", "AI-geletterdheid"], publication="2026-03-01"),
    record("inholland-holli-ai-feedback-leerpartner", "Holli en AI-feedback als leerpartner", "practice_example", "Praktijkvoorbeeld", "Hogeschool Inholland en Universiteit Twente",
           "Twee toegepaste voorbeelden waarin generatieve AI reflectiegesprekken ondersteunt en narratieve feedback helpt formuleren, met onderzoek naar de effecten op leren.",
           "Laten zien hoe AI als begeleide leerpartner kan worden ontworpen en geëvalueerd.",
           ["Docenten", "Studenten", "Onderzoekers", "Onderwijsontwikkelaars"], ["HBO", "WO", "Onderzoek"],
           ["Praktijkvoorbeelden", "Lesgeven en leren met AI", "Onderzoek"],
           "https://pretalx.surf.nl/surf-onderwijsdagen-2025/talk/PY9DC8/",
           ["Holli", "Inholland", "Universiteit Twente", "AI-feedback", "reflection"]),
    record("surf-community-ai-in-education", "SURF Community AI in Education", "community", "Community", "SURF",
           "Open kenniscommunity met artikelen, bijeenkomsten en uitwisseling over AI in onderwijs en onderzoek.",
           "Professionals en onderzoekers verbinden rond actuele AI-vraagstukken en praktijkkennis.",
           ["Docenten", "Onderzoekers", "Onderwijsadviseurs", "IT-professionals"], ["MBO", "HBO", "WO", "Onderzoek"],
           ["Professionalisering", "Praktijkvoorbeelden", "Onderzoek"],
           "https://communities.surf.nl/ai-in-education",
           ["SURF Communities", "AI in Education", "community", "kennisdeling"]),
]


def normalized(value):
    return " ".join(str(value).casefold().split()).rstrip("/")


def update_nro_to_nko(records):
    """Verwerk de officiële naamswijziging per 1 januari 2026."""
    for existing in records:
        if existing.get("id") != "nationaal-regieorgaan-onderwijsonderzoek-nro":
            continue
        existing["title"] = "Nationaal Kennisinstituut Onderwijs (NKO)"
        existing["providerName"] = "Nationaal Kennisinstituut Onderwijs"
        existing["description"] = "Nationaal kennisinstituut dat onderwijsonderzoek programmeert, financiert en verbindt met de onderwijspraktijk; tot 2026 bekend als NRO."
        existing["purpose"] = "Onderwijsonderzoek, kennisbenutting en evidence-informed onderwijs versterken"
        existing["sourceUrls"] = [{"label": "Officiële website", "url": "https://www.nko.nl/", "sourceType": "official"}]
        existing["lastVerified"] = VERIFIED
        existing["verificationStatus"] = "verified"
        existing["keywords"] = sorted(set(existing.get("keywords", []) + ["NKO", "NRO", "Nationaal Kennisinstituut Onderwijs"]))
        existing.setdefault("changeHistory", []).append({
            "date": VERIFIED,
            "type": "updated",
            "summary": "Naam en bron bijgewerkt na de overgang van NRO naar Nationaal Kennisinstituut Onderwijs."
        })
        return
    raise SystemExit("Import gestopt: het bestaande NRO-record is niet gevonden")


def main():
    records = json.loads(RECORDS_PATH.read_text(encoding="utf-8"))
    update_nro_to_nko(records)

    ids = {existing["id"] for existing in records}
    titles = {normalized(existing["title"]) for existing in records}
    urls = {normalized(source["url"]) for existing in records for source in existing.get("sourceUrls", [])}
    for new_record in ITEMS:
        clashes = []
        if new_record["id"] in ids:
            clashes.append("id")
        if normalized(new_record["title"]) in titles:
            clashes.append("titel")
        if normalized(new_record["sourceUrls"][0]["url"]) in urls:
            clashes.append("bron-URL")
        if clashes:
            raise SystemExit(f"Import gestopt: {new_record['title']} botst op {', '.join(clashes)}")
        ids.add(new_record["id"])
        titles.add(normalized(new_record["title"]))
        urls.add(normalized(new_record["sourceUrls"][0]["url"]))

    records.extend(ITEMS)
    RECORDS_PATH.write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    metadata = json.loads(META_PATH.read_text(encoding="utf-8"))
    metadata.update({"version": "Werkversie 0.5", "updated": "21 juli 2026", "recordCount": len(records)})
    META_PATH.write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Toegevoegd: {len(ITEMS)}; NRO bijgewerkt naar NKO; canoniek totaal: {len(records)}")


if __name__ == "__main__":
    main()

