"""Add the source-reviewed Dutch-language book tranche of 2 October 2026."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RECORDS_PATH = ROOT / "data" / "records.json"
VERIFIED = "2026-10-02"


def book(
    identifier: str,
    title: str,
    provider: str,
    authors: list[str],
    category: str,
    isbn: str,
    year: int,
    description: str,
    purpose: str,
    audiences: list[str],
    themes: list[str],
    official_url: str,
    *,
    subtype: str = "Paperback",
    sectors: list[str] | None = None,
    keywords: list[str] | None = None,
    notes: str,
    page_count: int | None = None,
    publication_date: str | None = None,
    geography: str = "Nederland",
    access: str = "paid",
    cost: str = "paid",
    availability: str | None = None,
    extra_sources: list[dict] | None = None,
) -> dict:
    record = {
        "id": identifier,
        "title": title,
        "recordType": "book",
        "legacyType": "Boek",
        "subtype": subtype,
        "providerName": provider,
        "authors": authors,
        "bookCategory": category,
        "isbn": isbn,
        "publicationYear": year,
        "description": description,
        "purpose": purpose,
        "audiences": audiences,
        "sectors": sectors or [],
        "themes": themes,
        "status": "available",
        "availabilityText": availability or "Verkrijgbaar via de uitgever of boekhandel.",
        "publicationDate": publication_date,
        "lastVerified": VERIFIED,
        "verificationStatus": "verified",
        "sourceUrls": [
            {"label": "Officiële bron", "url": official_url, "sourceType": "official"},
            *(extra_sources or []),
        ],
        "relatedIds": [],
        "parentIds": [],
        "childIds": [],
        "geographicScope": geography,
        "accessType": access,
        "costType": cost,
        "language": ["nl"],
        "keywords": keywords or [],
        "notes": notes,
        "changeHistory": [{
            "date": VERIFIED,
            "type": "added",
            "summary": "Toegevoegd in de brongecontroleerde boekentranche van 2 oktober 2026.",
        }],
        "commercialStatus": "unknown",
    }
    if page_count is not None:
        record["pageCount"] = page_count
    return record


ITEMS = [
    book(
        "boek-de-big-data-revolutie",
        "De big data-revolutie",
        "Maven Publishing",
        ["Viktor Mayer-Schönberger", "Kenneth Cukier"],
        "reading",
        "9789490574901",
        2013,
        "Vroege synthese over de omslag van steekproeven naar grootschalige data-analyse en de gevolgen daarvan voor voorspellen, beslissen en organiseren.",
        "De ideeëngeschiedenis van dataficatie en datagedreven besluitvorming helpen herkennen bij onderwijs- en organisatievraagstukken.",
        ["Bestuurders", "Beleidsmakers", "Informatiemanagers", "Onderzoekers"],
        ["Data en infrastructuur", "Beleid en governance", "Publieke waarden en ethiek"],
        "https://www.boom.nl/management/alle-uitgaven/100-4949_De-big-data-revolutie",
        keywords=["big data", "dataficatie", "voorspellen", "besluitvorming", "Mayer-Schönberger"],
        notes="Historisch basisboek uit 2013, van vóór de AVG, de AI Act en generatieve AI. Gebruik de voorbeelden en voorspellingen niet als actuele effectevidentie of technische leidraad.",
    ),
    book(
        "boek-de-data-economie",
        "De data-economie",
        "Maven Publishing",
        ["Viktor Mayer-Schönberger", "Thomas Ramge"],
        "reading",
        "9789492493330",
        2018,
        "Analyse van datarijke markten, digitale tussenpersonen, bedrijfscontrole en de mogelijke verschuiving van geld- naar datagedreven coördinatie.",
        "Bestuurders en beleidsmakers laten onderzoeken hoe datatoegang, marktmacht en menselijke keuze samenhangen met digitale infrastructuur.",
        ["Bestuurders", "Beleidsmakers", "Informatiemanagers", "Onderzoekers"],
        ["Data en infrastructuur", "Beleid en governance", "Publieke waarden en ethiek"],
        "https://www.mavenpublishing.nl/boeken/de-data-economie",
        page_count=280,
        publication_date="2018-01-24",
        keywords=["data-economie", "marktmacht", "digitale markten", "datatoegang", "Mayer-Schönberger"],
        notes="Het boek verdedigt een uitgesproken economische these en is niet onderwijsspecifiek. Voorspellingen over marktstructuur en welvaartsverdeling zijn geen vastgestelde uitkomsten. Een Boom-productpagina noemt afwijkend hardback en 304 pagina's; Bureau ISBN en brede bibliografische metadata ondersteunen voor dit ISBN paperback en 280 pagina's, die de Atlas daarom volgt.",
        extra_sources=[
            {
                "label": "Bureau ISBN",
                "url": "https://metadata.isbn.nl/1028239/de-data-economie.html",
                "sourceType": "authoritative",
            },
            {
                "label": "Bibliografische productpagina",
                "url": "https://www.bol.com/nl/nl/f/data-kapitalisme/9200000078814510/",
                "sourceType": "secondary",
            },
        ],
    ),
    book(
        "boek-framers",
        "Framers: Wat mensen beter kunnen dan computers",
        "Maven Publishing",
        ["Kenneth Cukier", "Viktor Mayer-Schönberger", "Francis de Véricourt"],
        "reading",
        "9789493213272",
        2022,
        "Toegankelijke verkenning van framing: het menselijke vermogen om situaties vanuit verschillende modellen te duiden en zo alternatieven te ontwerpen.",
        "Menselijke oordeelsvorming, perspectiefwisseling en probleemdefinitie expliciet maken naast geautomatiseerde analyse.",
        ["Bestuurders", "Docenten", "Beleidsmakers", "Onderwijsontwikkelaars"],
        ["AI-geletterdheid", "Publieke waarden en ethiek", "Professionalisering"],
        "https://www.mavenpublishing.nl/boeken/framers",
        page_count=256,
        publication_date="2022-05-10",
        keywords=["framing", "menselijk oordeel", "probleemdefinitie", "verbeelding", "Mayer-Schönberger"],
        notes="Argumentatieve publiekssynthese, geen bewijs dat computers principieel nooit kunnen framen of dat de beschreven aanpak onderwijsuitkomsten verbetert.",
        extra_sources=[{
            "label": "Bureau ISBN",
            "url": "https://metadata.isbn.nl/1535881/framers.html",
            "sourceType": "authoritative",
        }],
    ),
    book(
        "boek-de-glazen-kooi",
        "De glazen kooi: Wat automatisering met ons doet",
        "Maven Publishing",
        ["Nicholas Carr"],
        "reading",
        "9789491845345",
        2014,
        "Kritische beschouwing van automatisering, uitbesteding van denktaken, automatiseringsbias en het mogelijke verlies van geoefende menselijke vaardigheden.",
        "Vragen aanscherpen over wanneer automatisering ondersteunt en wanneer zij professionele oordeels- en correctiecapaciteit verzwakt.",
        ["Bestuurders", "Docenten", "Beleidsmakers", "Professionals"],
        ["Publieke waarden en ethiek", "Beleid en governance", "Professionalisering"],
        "https://www.mavenpublishing.nl/boeken/de-glazen-kooi",
        keywords=["automatisering", "deskilling", "automatiseringsbias", "menselijke regie", "correctiecapaciteit"],
        notes="Verhalend boek met vooral pre-generatieve-AI-casussen. Gebruik het als kritische lens, niet als actuele effectstudie van AI in het onderwijs.",
    ),
    book(
        "boek-de-platformsamenleving",
        "De platformsamenleving: Strijd om publieke waarden in een online wereld",
        "Amsterdam University Press",
        ["José van Dijck", "Thomas Poell", "Martijn de Waal"],
        "study",
        "9789462984615",
        2016,
        "Analyse van platformmechanismen zoals dataficatie, selectie en commercialisering en hun gevolgen voor publieke waarden, waaronder in het hoger onderwijs.",
        "Onderwijs als publiek domein verbinden met platformmacht, infrastructuurkeuzes en institutionele verantwoordelijkheid.",
        ["Bestuurders", "Beleidsmakers", "Onderzoekers", "Informatiemanagers"],
        ["Data en infrastructuur", "Publieke waarden en ethiek", "Beleid en governance"],
        "https://www.aup.nl/nl/book/9789462984615/de-platformsamenleving",
        page_count=180,
        publication_date="2016-11-10",
        sectors=["HBO", "WO", "Overheid"],
        keywords=["platformisering", "publieke waarden", "dataficatie", "MOOC", "onderwijsinfrastructuur"],
        notes="Open-access analyse uit het pre-generatieve-AI-tijdperk. De Nederlandse editie en de uitgebreidere Engelse uitgave zijn geen identieke edities.",
        access="public",
        cost="freemium",
        availability="Open access te lezen en als betaalde paperback of e-book verkrijgbaar.",
    ),
    book(
        "boek-doe-zelf-normaal",
        "Doe zelf normaal",
        "Prometheus",
        ["Maxim Februari"],
        "reading",
        "9789044650853",
        2023,
        "Filosofisch-juridisch essay over menselijk recht, democratische normering en bestuurlijke verantwoordelijkheid in een samenleving die steeds sterker door data wordt gestuurd.",
        "De vraag centraal stellen wie normen bepaalt en waar menselijke afweging en tegenspraak georganiseerd moeten blijven.",
        ["Bestuurders", "Beleidsmakers", "Juristen", "Onderwijsprofessionals"],
        ["Publieke waarden en ethiek", "Beleid en governance", "Data en infrastructuur"],
        "https://www.boom.nl/filosofie/alle-uitgaven/100-15130_Doe-zelf-normaal",
        page_count=144,
        subtype="Hardback",
        keywords=["rechtsstaat", "datasturing", "menselijke normering", "democratie", "autonomie"],
        notes="Normatief essay, geen geldende juridische norm of empirische evaluatie. Juridische actualiteit moet aan primaire rechtsbronnen worden getoetst.",
    ),
    book(
        "boek-de-tech-coup",
        "De tech coup",
        "Atlas Contact",
        ["Marietje Schaake"],
        "reading",
        "9789045052793",
        2025,
        "Analyse van de groeiende bestuurlijke macht van technologiebedrijven en voorstellen om democratische controle en publieke verantwoordelijkheid te herstellen.",
        "Afhankelijkheden van commerciële AI-infrastructuur en de bestuurlijke ruimte van publieke onderwijsinstellingen bespreekbaar maken.",
        ["Bestuurders", "Beleidsmakers", "Informatiemanagers", "Toezichthouders"],
        ["Beleid en governance", "Data en infrastructuur", "Publieke waarden en ethiek"],
        "https://www.atlascontact.nl/boek/de-tech-coup/",
        page_count=392,
        keywords=["big tech", "democratische controle", "marktmacht", "AI-infrastructuur", "toezicht"],
        notes="Politiek en beleidsmatig betoog met tijdgevoelige voorbeelden. Niet gebruiken als zelfstandige bron voor actuele wetgeving, marktaandelen of causale effecten.",
    ),
    book(
        "boek-atlas-van-de-digitale-wereld",
        "Atlas van de digitale wereld",
        "Boom",
        ["Haroon Sheikh"],
        "reading",
        "9789024468355",
        2024,
        "Compacte kaart van de digitale wereld als gelaagde infrastructuur, met aandacht voor chips, netwerken, cloud, platforms, data en geopolitieke afhankelijkheden.",
        "AI-keuzes in onderwijs verbinden met de onderliggende digitale stack, soevereiniteit en strategische afhankelijkheden.",
        ["Bestuurders", "Beleidsmakers", "Informatiemanagers", "IT-professionals"],
        ["Data en infrastructuur", "Beleid en governance", "Publieke waarden en ethiek"],
        "https://www.nt2.nl/nl/auteur/110-385_Sheikh/100-17323_Atlas-van-de-digitale-wereld",
        page_count=96,
        keywords=["digitale stack", "digitale soevereiniteit", "geopolitiek", "cloud", "infrastructuur"],
        notes="Beknopte conceptuele en geopolitieke verkenning; geen volledige technische inventaris of onderwijsspecifieke effectanalyse.",
    ),
    book(
        "boek-het-internet-is-stuk",
        "Het internet is stuk",
        "De Geus",
        ["Marleen Stikker"],
        "reading",
        "9789044542677",
        2019,
        "Essay over verlies van digitale soevereiniteit, concentratie van internetmacht en publieke alternatieven waarin mens en democratische waarden centraal staan.",
        "Publieke digitale infrastructuur en alternatieven voor afhankelijkheid van dominante technologiebedrijven helpen doordenken.",
        ["Bestuurders", "Beleidsmakers", "Informatiemanagers", "Onderwijsprofessionals"],
        ["Data en infrastructuur", "Publieke waarden en ethiek", "Beleid en governance"],
        "https://waag.org/nl/hetinternetisstuk/",
        publication_date="2019-11-28",
        keywords=["digitale soevereiniteit", "internet", "big tech", "publieke infrastructuur", "democratie"],
        notes="Pleidooi uit 2019 en dus van vóór de huidige generatieve-AI-golf. De gratis PDF heeft een CC BY-SA-licentie; andere uitvoeringen zijn betaald.",
        access="public",
        cost="freemium",
        availability="Gratis als PDF onder CC BY-SA; ook in betaalde uitvoeringen verkrijgbaar.",
        extra_sources=[{
            "label": "Officiële uitgeverspagina",
            "url": "https://www.singeluitgeverijen.nl/de-geus/boek/het-internet-is-stuk/",
            "sourceType": "official",
        }],
    ),
    book(
        "boek-algoritmes-aan-de-macht",
        "Algoritmes aan de macht",
        "De Geus",
        ["Hannah Fry"],
        "reading",
        "9789044538830",
        2018,
        "Publieksboek over geautomatiseerde beslissingen, privacy, foutkansen en de afweging tussen menselijk en algoritmisch gezag.",
        "Professionals laten herkennen waar een algoritme ondersteunt, waar het beslist en welke menselijke afweging niet mag verdwijnen.",
        ["Docenten", "Bestuurders", "Beleidsmakers", "Studenten"],
        ["AI-geletterdheid", "Publieke waarden en ethiek", "Beleid en governance"],
        "https://www.singeluitgeverijen.nl/de-geus/boek/algoritmes-aan-de-macht/",
        subtype="E-book",
        publication_date="2018-12-11",
        keywords=["algoritmen", "geautomatiseerde besluiten", "privacy", "menselijk oordeel", "risico"],
        notes="Toegankelijke publiekswetenschap met voorbeelden uit 2018, vóór generatieve AI en de AI Act. Geen actuele technische of juridische handleiding.",
        availability="Als e-book verkrijgbaar via de uitgever en boekhandel.",
    ),
    book(
        "boek-de-ai-revolutie",
        "De AI-revolutie",
        "Uitgeverij Balans",
        ["Maarten Sukel"],
        "reading",
        "9789463823098",
        2024,
        "Toegankelijke inleiding tot AI en de maatschappelijke invloed ervan op onder meer onderwijs, werk, zorg, oorlog, ongelijkheid en beeldvorming.",
        "Een breed startpunt bieden voor gesprekken over technische mogelijkheden, maatschappelijke gevolgen en bestuurlijke keuzes rond AI.",
        ["Docenten", "Studenten", "Bestuurders", "Beleidsmakers"],
        ["AI-geletterdheid", "Publieke waarden en ethiek", "Beleid en governance"],
        "https://www.uitgeverijbalans.nl/boeken/de-ai-revolutie/",
        page_count=192,
        publication_date="2024-01-24",
        keywords=["AI-inleiding", "maatschappelijke impact", "ChatGPT", "ongelijkheid", "onderwijs"],
        notes="Breed en snel verouderend overzicht, geen systematische literatuurreview. Controleer actuele modelcapaciteiten en effectclaims in primaire bronnen.",
    ),
    book(
        "boek-ai-alsmaar-intelligenter",
        "AI: Alsmaar intelligenter",
        "De Bezige Bij",
        ["Stefan Buijsman"],
        "reading",
        "9789403104317",
        2020,
        "Inleidend publieksboek over de werking, geschiedenis, mogelijkheden en beperkingen van algoritmen en kunstmatige intelligentie.",
        "Basisbegrippen en kritische vragen toegankelijk maken voor lezers zonder technische vooropleiding.",
        ["Docenten", "Studenten", "Onderwijsprofessionals", "Algemeen publiek"],
        ["AI-geletterdheid", "Publieke waarden en ethiek"],
        "https://www.debezigebij.nl/boek/ai-alsmaar-intelligenter/",
        page_count=224,
        subtype="E-book",
        publication_date="2020-06-11",
        keywords=["AI-basiskennis", "algoritmen", "deepfakes", "gezichtsherkenning", "beperkingen"],
        notes="Introductie uit 2020 en dus van vóór de brede inzet van generatieve AI. Gebruik niet voor actuele productmogelijkheden of wetgeving.",
        availability="Als e-book en luisterboek verkrijgbaar via de uitgever.",
    ),
    book(
        "boek-in-de-schaduw-van-ai",
        "In de schaduw van AI",
        "Atlas Contact",
        ["Madhumita Murgia"],
        "reading",
        "9789047016366",
        2024,
        "Journalistieke casussen over mensen die geraakt worden door AI in onder meer zorg, publieke dienstverlening, gezichtsherkenning en werk.",
        "De menselijke en verdelingseffecten achter abstracte AI-systemen zichtbaar maken en vragen naar zeggenschap en herstel openen.",
        ["Bestuurders", "Beleidsmakers", "Docenten", "Onderzoekers"],
        ["Publieke waarden en ethiek", "Beleid en governance", "Data en infrastructuur"],
        "https://www.atlascontact.nl/boek/in-de-schaduw-van-ai/",
        page_count=296,
        publication_date="2024-07-03",
        keywords=["menselijke impact", "discriminatie", "uitbuiting", "zeggenschap", "publieke dienstverlening"],
        notes="Journalistieke, internationale casussen; geen causale synthese en niet zonder aanvullende bronnen te generaliseren naar Nederlandse onderwijsinstellingen.",
    ),
    book(
        "boek-filterwereld",
        "Filterwereld",
        "Uitgeverij Ten Have",
        ["Kyle Chayka"],
        "reading",
        "9789025911058",
        2024,
        "Culturele analyse van aanbevelingsalgoritmen en de manier waarop meer-van-hetzelfde selectie, smaak en digitale omgevingen kan homogeniseren.",
        "Monocultuur, convergentie en verlies van keuzeruimte als bestuurlijke gevolgen van algoritmische selectie helpen herkennen.",
        ["Bestuurders", "Docenten", "Beleidsmakers", "Onderzoekers"],
        ["Publieke waarden en ethiek", "Data en infrastructuur", "AI-geletterdheid"],
        "https://www.uitgeverijtenhave.nl/boek/filterwereld/",
        page_count=320,
        publication_date="2024-11-07",
        keywords=["aanbevelingsalgoritmen", "monocultuur", "convergentie", "selectie", "vrije wil"],
        notes="Cultureel-journalistiek betoog, geen onderwijsspecifieke causale effectstudie. De paperbackeditie en bibliografische gegevens zijn op de officiële uitgeverspagina gecontroleerd.",
    ),
    book(
        "boek-het-masker-van-ai",
        "Het masker van AI",
        "LannooCampus",
        ["Wim Casteels"],
        "reading",
        "9789020989816",
        2025,
        "Toegankelijke verkenning van AI-geletterdheid, ecologische kosten, bigtechmacht, discriminatie, autonomie en beïnvloeding van publieke opinie.",
        "Technische basiskennis verbinden met maatschappelijke impact en kritische reflectie over eerlijkheid, inclusie en macht.",
        ["Docenten", "Studenten", "Professionals", "Beleidsmakers"],
        ["AI-geletterdheid", "Publieke waarden en ethiek", "Data en infrastructuur"],
        "https://www.lannoo.com/nl-nl/economie-management/het-masker-van-ai-9789020989816",
        page_count=232,
        publication_date="2025-10-20",
        geography="Europa",
        keywords=["AI-geletterdheid", "big tech", "ecologische impact", "discriminatie", "autonomie"],
        notes="Toegankelijke auteurssynthese. De brede maatschappelijke duiding is geen onafhankelijke effectstudie of vervanging voor specialistische juridische en technische bronnen.",
    ),
    book(
        "boek-co-intelligentie-2026",
        "Co-intelligentie: 2026-editie",
        "Maven Publishing",
        ["Ethan Mollick"],
        "reading",
        "9789493434271",
        2025,
        "Geactualiseerde praktijkgerichte synthese over samenwerken met generatieve AI in werk en onderwijs en over de veranderende rolverdeling tussen mens en model.",
        "Professionals laten experimenteren met AI terwijl menselijk oordeel, controle en verantwoordelijkheid expliciet blijven.",
        ["Docenten", "Professionals", "Bestuurders", "Studenten"],
        ["AI-geletterdheid", "Professionalisering", "Lesgeven en leren met AI"],
        "https://www.mavenpublishing.nl/boeken/co-intelligentie-2026-editie",
        publication_date="2025-11-25",
        keywords=["generatieve AI", "mens-AI samenwerking", "werk", "onderwijs", "experimenteren"],
        notes="Praktijkgerichte auteursynthese met snel verouderende voorbeelden. Aanbevelingen zijn geen onafhankelijk bewijs van leerwinst, productiviteit of veiligheid.",
        extra_sources=[{
            "label": "Bureau ISBN",
            "url": "https://metadata.isbn.nl/2034768/co-intelligentie-2026-editie.html",
            "sourceType": "authoritative",
        }],
    ),
    book(
        "boek-algoritmes-en-grondrechten",
        "Algoritmes en grondrechten",
        "Boom Juridisch",
        ["Janneke Gerards", "Remco Nehmelman", "Max Vetzo"],
        "study",
        "9789462905412",
        2018,
        "Juridische studie naar de mogelijke gevolgen van big data, IoT en AI voor vrijheid, gelijkheid, privacy en procedurele rechten in Nederland.",
        "Grondrechten en rechtsbescherming vroeg in ontwerp, inkoop en gebruik van algoritmische systemen laten meewegen.",
        ["Juristen", "Beleidsmakers", "Bestuurders", "Onderzoekers"],
        ["AI Act en wetgeving", "Publieke waarden en ethiek", "Beleid en governance"],
        "https://www.boom.nl/juridisch/alle-uitgaven/100-12256_Algoritmes-en-grondrechten",
        page_count=244,
        keywords=["grondrechten", "autonomie", "gelijke behandeling", "privacy", "rechtsbescherming"],
        notes="Juridische analyse uit 2018, van vóór de AI Act en latere rechtspraak. Gebruik voor het analysekader; controleer actuele verplichtingen altijd in primaire rechtsbronnen.",
    ),
    book(
        "boek-juridische-aspecten-algoritmen",
        "Juridische aspecten van algoritmen die besluiten nemen",
        "Boom Juridisch",
        ["Stefan Kulk", "Stijn van Deursen", "Martje Boekema", "Vicky Breemen", "Susanne Heeger", "Stefan Philipsen", "Thom Snijders", "Anouk Wouters"],
        "study",
        "9789462908390",
        2020,
        "Onderzoeksboek over kansen en risico's van algoritmische besluitvorming voor publieke waarden en rechtsbescherming, gebaseerd op WODC-onderzoek.",
        "Besluitvormingsketens en juridische waarborgen analyseren voordat algoritmen in publieke of onderwijsprocessen worden ingezet.",
        ["Juristen", "Beleidsmakers", "Bestuurders", "Onderzoekers"],
        ["AI Act en wetgeving", "Publieke waarden en ethiek", "Beleid en governance"],
        "https://www.boom.nl/juridisch/100-12618_Juridische-aspecten-van-algoritmen-die-besluiten-nemen",
        page_count=276,
        keywords=["algoritmische besluitvorming", "rechtsbescherming", "publieke waarden", "WODC", "besluiten"],
        notes="Onderzoek uit 2020, vóór de AI Act. Het biedt juridische probleemanalyse maar geen vaststelling van huidige compliance-eisen of onderwijseffecten.",
    ),
    book(
        "boek-digitale-geletterdheid-werkvormenboek",
        "Het digitale geletterdheid werkvormenboek",
        "Boom uitgevers Amsterdam",
        ["Pim Renou", "Josien Boetje", "Patrick Dooyeweerd", "Rashida Nanhekhan"],
        "practice",
        "9789024474615",
        2026,
        "Verzameling activerende werkvormen over digitale systemen, media, data, AI, programmeren, privacy en de gedigitaliseerde wereld.",
        "Leraren concrete manieren bieden om digitale en kritische AI-geletterdheid met leerdoelen en differentiatie in lessen te verwerken.",
        ["Docenten", "Leraren in opleiding", "Onderwijsontwikkelaars"],
        ["AI-geletterdheid", "Curriculumontwikkeling", "Lesgeven en leren met AI"],
        "https://www.boom.nl/hoger-onderwijs/docentprofessionalisering/100-20531_Het-digitale-geletterdheid-werkvormenboek",
        page_count=240,
        publication_date="2026-09-04",
        sectors=["PO", "VO", "HBO"],
        keywords=["digitale geletterdheid", "werkvormen", "kritische AI-geletterdheid", "kerndoelen", "differentiatie"],
        notes="Breder dan AI: artificiële intelligentie is één inhoudsdomein naast media, data, programmeren en veiligheid. De werkvormen zijn aanbod, geen aangetoond leereffect.",
        extra_sources=[{
            "label": "Bureau ISBN",
            "url": "https://metadata.isbn.nl/2122763/het-digitale-geletterdheid-werkvormenboek.html",
            "sourceType": "authoritative",
        }],
    ),
    book(
        "boek-handboek-digitale-didactiek",
        "Handboek digitale didactiek",
        "Boom",
        ["Robert Mol"],
        "practice",
        "9789024465743",
        2025,
        "Handboek voor doelgerichte technologiekeuze in onderwijs, met kaders voor privacy, inclusie en digitale veiligheid en een afzonderlijk hoofdstuk over generatieve AI.",
        "Docenten technologie en generatieve AI laten verbinden aan leerdoelen, didactiek, feedback en professioneel oordeel.",
        ["Docenten", "Onderwijsontwikkelaars", "Leraren in opleiding"],
        ["Lesgeven en leren met AI", "Professionalisering", "Privacy en AVG"],
        "https://www.boom.nl/hoger-onderwijs/aanbod-boom-academie/100-19799_Handboek-digitale-didactiek",
        page_count=368,
        sectors=["PO", "VO", "MBO", "HBO", "WO"],
        keywords=["digitale didactiek", "generatieve AI", "lesontwerp", "privacy", "feedback"],
        notes="Breed handboek digitale didactiek; generatieve AI is één hoofdstuk en loopt ook door werkvormen. Toolvoorbeelden en prompts verouderen en bewijzen geen effectiviteit. De Boom-productpagina noemt 300 pagina's, maar het officiële inkijkexemplaar loopt tot pagina 366 en bibliografische metadata vermeldt 368; de Atlas volgt daarom 368.",
        extra_sources=[
            {
                "label": "Officieel inkijkexemplaar",
                "url": "https://www.boom.nl/media/69/inkijkexemplaar_handboek_digitale_didactiek%281%29.pdf",
                "sourceType": "official",
            },
            {
                "label": "Bibliografische productpagina",
                "url": "https://www.bol.com/nl/nl/p/handboek-digitale-didactiek/9300000238153528/",
                "sourceType": "secondary",
            },
        ],
    ),
    book(
        "boek-ai-ergo-sum",
        "AI Ergo Sum",
        "Open Press Tilburg University",
        ["Hannah van den Bosch (red.)"],
        "reading",
        "9789403870809",
        2026,
        "Open essaybundel van Tilburgse wetenschappers over menselijkheid, autonomie, verantwoordelijkheid, kennis en onderwijs in relatie tot AI.",
        "Ruimte bieden voor interdisciplinaire reflectie en professionele weerstand wanneer AI menselijke vorming of verantwoordelijkheid raakt.",
        ["Docenten", "Studenten", "Onderzoekers", "Bestuurders"],
        ["Publieke waarden en ethiek", "AI-geletterdheid", "Lesgeven en leren met AI"],
        "https://openpress.tilburguniversity.edu/projects/ai-ergo-sum",
        publication_date="2026-06-26",
        keywords=["Bildung", "mensbeeld", "autonomie", "professionele weerstand", "AI-agents"],
        notes="Interdisciplinaire essaybundel, geen empirische evaluatie van AI-effecten. De online tekst en PDF zijn beschikbaar onder CC BY 4.0; de paperback is betaald.",
        access="public",
        cost="freemium",
        availability="Gratis online en als PDF onder CC BY 4.0; paperback verkrijgbaar.",
        extra_sources=[{
            "label": "Bureau ISBN",
            "url": "https://metadata.isbn.nl/2127166/ai-ergo-sum.html",
            "sourceType": "authoritative",
        }],
    ),
    book(
        "boek-universiteit-als-spiegel",
        "De universiteit als spiegel van de samenleving",
        "Open Press Tilburg University",
        ["Paul van Geest", "Emile Aarts", "Ronald de Jong"],
        "study",
        "9789403874104",
        2026,
        "Analyse van AI als systeemtechnologie voor universitair onderwijs, onderzoek, bestuur, academische vorming, integriteit, leiderschap en mensbeeld.",
        "Bestuurders en academische professionals helpen expliciteren welke kennis-, waarden- en verantwoordelijkheidskeuzes AI van universiteiten vraagt.",
        ["Bestuurders", "Docenten", "Onderzoekers", "Beleidsmakers"],
        ["Beleid en governance", "Onderzoek", "Publieke waarden en ethiek"],
        "https://openpress.tilburguniversity.edu/projects/de-universiteit-als-spiegel-van-de-samenleving",
        sectors=["WO", "Onderzoek"],
        keywords=["universiteit", "academische integriteit", "mensbeeld", "leiderschap", "AI-governance"],
        notes="Reflectieve synthese en pleidooi, geen onafhankelijke effectstudie. De online tekst, PDF en epub zijn beschikbaar onder CC BY 4.0; de gedrukte uitgave is betaald.",
        access="public",
        cost="freemium",
        availability="Gratis online, als PDF en als epub onder CC BY 4.0; gedrukte uitgave verkrijgbaar.",
    ),
    book(
        "boek-toetsen-in-verbinding",
        "Toetsen in verbinding",
        "Telos Uitgevers",
        ["Antoinette van Berkel", "Dominique Sluijsmans"],
        "practice",
        "9789083660011",
        2026,
        "Bundel met perspectieven en praktijkvoorbeelden voor eerlijk, transparant en leergericht toetsen in het hoger onderwijs, waaronder toetsen met generatieve AI.",
        "Toetsing verbinden met leren, professionele identiteit, curriculum, dialoog en gedeelde verantwoordelijkheid in een AI-rijke context.",
        ["Docenten", "Toetsdeskundigen", "Onderwijsontwikkelaars", "Beleidsmakers"],
        ["Toetsing en examinering", "Lesgeven en leren met AI", "Curriculumontwikkeling"],
        "https://telos-uitgevers.nl/boeken/toetsen-in-verbinding/",
        publication_date="2026-03-19",
        sectors=["HBO", "WO"],
        keywords=["toetsing", "generatieve AI", "curriculum", "leergericht toetsen", "hoger onderwijs"],
        notes="AI is één context binnen een bredere toetsbundel. Bijdragen en praktijkvoorbeelden kunnen in methode en bewijskracht verschillen en bewijzen geen generiek effect.",
        extra_sources=[{
            "label": "Bureau ISBN",
            "url": "https://metadata.isbn.nl/2065469/toetsen-in-verbinding.html",
            "sourceType": "authoritative",
        }],
    ),
    book(
        "boek-ai-en-taal",
        "AI & taal",
        "LannooCampus",
        ["Walter Daelemans"],
        "study",
        "9789059964938",
        2026,
        "Kritische introductie tot taaltechnologie, grote taalmodellen en generatieve AI, met historische context en aandacht voor betekenis, redeneren, ethiek en grenzen.",
        "Studenten, docenten en professionals helpen taalmodellen technisch en maatschappelijk te doorgronden zonder in hype of simplificatie te vervallen.",
        ["Studenten", "Docenten", "Onderzoekers", "Professionals"],
        ["AI-geletterdheid", "Onderzoek", "Publieke waarden en ethiek"],
        "https://www.lannoo.com/nl-nl/taal-letterkunde/ai-taal-9789059964938",
        subtype="E-book",
        page_count=160,
        publication_date="2026-09-15",
        geography="Europa",
        keywords=["taaltechnologie", "grote taalmodellen", "generatieve AI", "redeneren", "ethiek"],
        notes="Kritische auteurssynthese, geen benchmark of onafhankelijke evaluatie van afzonderlijke modellen. Capaciteiten en beperkingen blijven tijdgevoelig.",
    ),
    book(
        "boek-ai-voor-de-klas",
        "AI voor de klas",
        "Leren met Actie",
        ["Jeroen Marbus", "Rogier van 't Veer"],
        "practice",
        "9789090404882",
        2025,
        "Praktijkboek over AI-didactiek, vakmanschap, beleid, toetsing, oudergesprekken en werkvormen voor PO, VO en MBO.",
        "Onderwijsteams helpen AI-keuzes te verbinden aan visie, vakdidactiek, privacy, autonomie en actief blijven denken.",
        ["Docenten", "Schoolleiders", "Opleiders", "Onderwijsteams"],
        ["Lesgeven en leren met AI", "Beleid en governance", "Toetsing en examinering"],
        "https://lerenmetactie.nl/aivoordeklas.php",
        subtype="Hardcover",
        page_count=150,
        publication_date="2025-08-22",
        sectors=["PO", "VO", "MBO"],
        keywords=["AI-didactiek", "professionele autonomie", "toetsing", "schoolbeleid", "werkvormen"],
        notes="Door de auteurs zelf uitgegeven praktijkboek. De beschreven aanpak en lezersreacties zijn geen onafhankelijke effectevaluatie; juridische uitspraken moeten apart worden geverifieerd.",
        extra_sources=[{
            "label": "Bibliografische productpagina",
            "url": "https://www.bol.com/nl/nl/p/ai-voor-de-klas-vakmanschap-in-tijdens-van-kunstmatige-intelligentie-hardcover/9300000235352597/",
            "sourceType": "secondary",
        }],
    ),
    book(
        "boek-keuzedeel-generatieve-ai",
        "Keuzedeel: Artificial Intelligence - werken met generatieve AI",
        "Educatieve Uitgeversgroep",
        ["Suzet Leeuwestein"],
        "study",
        "9789400243323",
        2026,
        "Leerwerkboek voor het mbo-keuzedeel over de werking van AI-tools en veilig en doelgericht gebruik van generatieve AI in verschillende beroepscontexten.",
        "Mbo-studenten gestructureerd laten oefenen met basiskennis, beroepsgerichte toepassing en verantwoord gebruik van generatieve AI.",
        ["Studenten", "Docenten"],
        ["AI-geletterdheid", "Curriculumontwikkeling", "Lesgeven en leren met AI"],
        "https://www.uitgeversgroep.nl/9789400243323-keuzedeel-artificial-intelligence-werken-met-generatieve-ai",
        subtype="Leerwerkboek met digitale licentie",
        sectors=["MBO"],
        keywords=["keuzedeel", "mbo", "generatieve AI", "beroepscontext", "leerwerkboek"],
        notes="Commercieel curriculumproduct met uitgeversbeschrijving en docentondersteuning. Opname zegt niets over onafhankelijke kwaliteit, leerwinst of volledige kwalificatiedekking.",
        availability="Papieren leerwerkboek met drie schooljaren toegang tot het digitale boek.",
    ),
]


def normalized(value: object) -> str:
    return " ".join(str(value).casefold().split()).rstrip("/")


def main() -> None:
    records = json.loads(RECORDS_PATH.read_text(encoding="utf-8"))
    positions = {record["id"]: index for index, record in enumerate(records)}
    batch_ids = {record["id"] for record in ITEMS}
    existing_titles = {
        normalized(record["title"])
        for record in records
        if record["id"] not in batch_ids
    }
    existing_isbns = {
        record.get("isbn")
        for record in records
        if record["id"] not in batch_ids and record.get("recordType") == "book"
    }
    added = 0
    updated = 0

    for new_record in ITEMS:
        if normalized(new_record["title"]) in existing_titles:
            raise SystemExit(f"Import gestopt: dubbele titel voor {new_record['title']}")
        if new_record["isbn"] in existing_isbns:
            raise SystemExit(f"Import gestopt: dubbel ISBN voor {new_record['title']}")
        existing_titles.add(normalized(new_record["title"]))
        existing_isbns.add(new_record["isbn"])
        if new_record["id"] in positions:
            records[positions[new_record["id"]]] = new_record
            updated += 1
        else:
            positions[new_record["id"]] = len(records)
            records.append(new_record)
            added += 1

    RECORDS_PATH.write_text(
        json.dumps(records, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Toegevoegd: {added}; bijgewerkt: {updated}; canoniek totaal: {len(records)}")


if __name__ == "__main__":
    main()
